apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaeger-pvolume
  namespace: monitoring-ns
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 67.67.67.101
    path: /mnt/k8sdata/jaeger
