apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
  namespace: monitoring-ns
spec:
  volumeName: jaeger-pvolume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
