apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring-ns
spec:
  volumeName: prometheus-pvolume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
