apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pvolume
  namespace: monitoring-ns
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/k8sdata/prometheus/
    server: 67.67.67.101
    readOnly: false
