apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pvolume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/k8sdata/mongodb
    server: 67.67.67.101
