apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv-volume
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/k8sdata/mssql/
    server: 67.67.67.101
    readOnly: false
