apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-deployment
    labels:
        app: mssql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mssql
    template:
        metadata:
            labels:
                app: mssql
        spec:
            containers:
            - name: mssql
              image: mcr.microsoft.com/mssql/server:2019-latest
              ports:
              - containerPort: 1433
              livenessProbe:
                tcpSocket:
                  port: 1433
                initialDelaySeconds: 15
                periodSeconds: 30
              env:
                - name: ACCEPT_EULA
                  value: "Y"
                - name: MSSQL_ENABLE_HADR
                  value: "1"
                - name: MSSQL_AGENT_ENABLED
                  value: "1"
                - name: MSSQL_SA_PASSWORD
                  valueFrom:
                    secretKeyRef:
                        name: mssql-secret
                        key: sa-password
                - name: MSSQL_PID
                  value: "Developer"
              volumeMounts:
                - name: mssql-volume
                  mountPath: "/var/opt/mssql"
            volumes:
                - name: mssql-volume
                  persistentVolumeClaim:
                    claimName: mssql-pvc
            tolerations:
              - key: "node.kubernetes.io/unreachable"
                operator: "Exists"
                effect: "NoExecute"
                tolerationSeconds: 10
              - key: "node.kubernetes.io/not-ready"
                operator: "Exists"
                effect: "NoExecute"
                tolerationSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
spec:
  selector:
    app: mssql
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 31433
